# Generated by Django 5.2.8 on 2025-11-26 15:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(help_text='Spotify ID of the track/album/artist being rated', max_length=64)),
                ('item_type', models.CharField(choices=[('track', 'Track'), ('album', 'Album'), ('artist', 'Artist')], help_text='Type of Spotify item being rated', max_length=10)),
                ('rating', models.DecimalField(decimal_places=2, help_text='Rating from 0.00 to 5.00.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'spotify_id', 'item_type')},
            },
        ),
    ]
