# Generated by Django 5.2.8 on 2025-11-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='item_name',
            field=models.CharField(blank=True, help_text='Readable name of the item (e.g. track/album/artist name).', max_length=255),
        ),
    ]
