# Generated by Django 5.2.8 on 2025-11-29 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rating_item_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(help_text='Spotify ID of the track/album/artist being reviewed', max_length=64)),
                ('item_type', models.CharField(choices=[('track', 'Track'), ('album', 'Album'), ('artist', 'Artist')], help_text='Type of Spotify item being reviewed', max_length=10)),
                ('item_name', models.CharField(blank=True, help_text='Human-readable name of the item (e.g. track/album/artist name).', max_length=255)),
                ('text', models.TextField(blank=True, help_text="User's review text (up to 10,000 characters).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'spotify_id', 'item_type')},
            },
        ),
    ]
